build:
  nodes:
    analysis:
        commands:
          - cd backend && npm install && npm test  # Install dependencies before running tests


# version: '1'

# # Build section to run in a Node.js container
# build:
#   image: node:18
#   commands:
#     - docker-compose exec backend npm install  # Install dependencies in backend container
#     - docker-compose exec frontend npm install  # Install dependencies in frontend container
#     - docker-compose exec frontend_customer npm install  # Install dependencies in frontend_customer container
#     - docker-compose exec simulation npm install  # Install dependencies in simulation container

# # Run tests in specific containers using docker-compose exec
# tests:
#   - name: Run tests in backend container
#     command: docker-compose exec backend npm test
#   - name: Run tests in frontend container
#     command: docker-compose exec frontend npm test
#   - name: Run tests in frontend_customer container
#     command: docker-compose exec frontend_customer npm test
#   - name: Run tests in simulation container
#     command: docker-compose exec simulation npm test

# after:
#   - echo "All tests completed."

# version: '1'

# # Build section to run in a Node.js container
# build:
#   image: node:18
#   commands:
#     - npm install  # Install dependencies in the Node.js container

# # Run tests in specific containers using docker-compose exec
# tests:
#   - name: Run tests in backend container
#     command: docker-compose exec backend npm test
#   # - name: Run tests in bike-brain container
#   #   command: docker-compose exec bike-brain npm test
#   # - name: Run tests in frontend container
#   #   command: docker-compose exec frontend npm test
#   # - name: Run tests in frontend_customer container
#   #   command: docker-compose exec frontend_customer npm test
#   # - name: Run tests in simulation container
#   #   command: docker-compose exec simulation npm test

# after:
#   - echo "All tests completed."
