services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment:
            - MONGO_DSN=${MONGO_DSN}
            - MONGO_URI=${MONGO_URI}
            - CLIENT_ID=${CLIENT_ID}
            - CLIENT_SECRET=${CLIENT_SECRET}
            - REDIRECT_URI=${REDIRECT_URI}
            - JWT_SECRET=${JWT_SECRET}
            - REDIRECT_URI_FRONTEND=${REDIRECT_URI_FRONTEND}
            - NODE_ENV=simulation # Test for data generation for simulation
        ports:
            - "5000:5000"
            - "5001:5001"
        networks:
            - app-network
        volumes:
            - ./backend:/app
            - /app/node_modules # Persist node_modules inside container to avoid overwriting
        depends_on:
            - mongodb # Make sure the database is built
        command:
            > # Run seeding script to populate the database first, then start the server
            sh -c "node ./data-generation/index.js && node ./database-config/seed.js && npm run nodemon"

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "5173:5173" # Changed to Vite default port
        networks:
            - app-network
        volumes:
            - ./frontend:/app
            - /app/node_modules # Persist node_modules inside container to avoid overwriting
        # Uncomment the lines below if file watching is not working as expected!
        # environment:
        #     - CHOKIDAR_USEPOLLING=true
        depends_on:
            - backend # Make sure that the backend is built and running

    frontend_customer:
        build:
            context: ./frontend_customer
            dockerfile: Dockerfile
        ports:
            - "1337:1337" # Changed to Vite default port
        networks:
            - app-network
        volumes:
            - ./frontend_customer:/app
            - /app/node_modules # Persist node_modules inside container to avoid overwriting
        # Uncomment the lines below if file watching is not working as expected!
        # environment:
        #     - CHOKIDAR_USEPOLLING=true
        depends_on:
            - backend # Make sure that the backend is built and running

    webapp:
        build:
            context: ./webapp
            dockerfile: Dockerfile
        ports:
            - "3000:3000" # Changed to Vite default port
        networks:
            - app-network
        volumes:
            - ./webapp:/app
            - /app/node_modules # Persist node_modules inside container to avoid overwriting
        # Uncomment the lines below if file watching is not working as expected!
        # environment:
        #     - CHOKIDAR_USEPOLLING=true
        depends_on:
            - backend # Make sure that the backend is built and running

    mongodb: # Need to create.env
        image: mongo
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db:/data/db
        ports:
            - "27017:27017"
        command: mongod --bind_ip_all
        networks:
            - app-network

    simulation:
        build:
            context: ./bike-brain
            dockerfile: Dockerfile
<<<<<<< HEAD
        environment:
            - BIKE_TOKEN=${BIKE_TOKEN}
=======
>>>>>>> 9149a7a (Add simulation service)
        networks:
            - app-network
        depends_on:
            - backend
        stdin_open: true
        tty: true
        command: /bin/sh
        # command: node sim-from-database.js

networks:
    app-network:
        driver: bridge
