services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        networks:
            - app-network

    webapp:
        build:
            context: ./webapp
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
